[project]
name = "ts"
version = "0.1.0"
description = "Telegram Secret Santa bot"
requires-python = ">=3.11"

dependencies = [
    "python-telegram-bot==22.5",
    "fastapi>=0.110",
    "uvicorn>=0.27"
]

[tool.uv]
package = false
